#!/usr/bin/env node
/*
 * Precompile a UI kit's JSX → plain JS using the SAME babel-standalone that the
 * browser used to run at runtime, so the output is identical to the old in-page
 * transform — just done once, at build time, instead of on every page load.
 *
 * Usage:  node build-jsx.js <kit-dir> <file1.jsx> <file2.jsx> ...
 * Writes: <kit-dir>/compiled/<file>.js   for each input, plus
 *         <kit-dir>/compiled/bundle.js   — all of them concatenated, IN THE ORDER GIVEN.
 *
 * ORDER MATTERS: the files are executed in sequence and later ones depend on globals set
 * by earlier ones, so the argument order must match the loader's. Pass every file the kit
 * loads, in load order, or the bundle will be incomplete or mis-ordered.
 *
 * Concatenation is safe because the compiled output only ever declares `function`s at top
 * level (Babel's _extends helper, and App) — duplicate function declarations are legal,
 * whereas a top-level const/let/class appearing in two files would be a hard SyntaxError
 * once merged into one script. The build verifies the bundle parses, so that fails here
 * rather than white-screening the site.
 *
 * After editing any .jsx in a precompiled kit you MUST re-run this and bump the
 * loader's ?v= — otherwise the site serves stale compiled JS.
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

// Load babel-standalone into a sandbox and grab the Babel global (it's a UMD bundle).
const babelSrc = fs.readFileSync(path.join(__dirname, 'vendor', 'babel.min.js'), 'utf8');
const mod = { exports: {} };
const sandbox = { self: {}, window: {}, module: mod, exports: mod.exports };
vm.createContext(sandbox);
vm.runInContext(babelSrc, sandbox, { filename: 'babel.min.js' });
const Babel = [
  sandbox.exports, mod.exports, sandbox.Babel,
  sandbox.window && sandbox.window.Babel, sandbox.self && sandbox.self.Babel,
].find(function (x) { return x && typeof x.transform === 'function'; });
if (!Babel || !Babel.transform) {
  console.error('ERROR: could not load Babel from vendor/babel.min.js');
  process.exit(1);
}

const [, , kitDir, ...files] = process.argv;
if (!kitDir || files.length === 0) {
  console.error('Usage: node build-jsx.js <kit-dir> <file1.jsx> ...');
  process.exit(1);
}

const outDir = path.join(kitDir, 'compiled');
fs.mkdirSync(outDir, { recursive: true });

let ok = 0;
const parts = [];
for (const file of files) {
  const inPath = path.join(kitDir, file);
  const src = fs.readFileSync(inPath, 'utf8');
  let code;
  try {
    code = Babel.transform(src, { presets: ['react'] }).code;
  } catch (e) {
    console.error('COMPILE FAIL ' + file + ': ' + (e && e.message || e));
    process.exit(1);
  }
  const outName = file.replace(/\.jsx$/, '.js');
  fs.writeFileSync(path.join(outDir, outName), code);
  // Keep a marker per section: a runtime stack trace in the bundle is otherwise very hard
  // to trace back to a source file.
  parts.push('/* ==== ' + file + ' ==== */\n' + code + '\n');
  ok++;
}

// Single-file bundle: one <script defer> the browser's preload scanner can discover, instead
// of 11 files fetched at runtime by JS (which the scanner cannot see, so they could not
// start until the rest of the head had executed).
const bundlePath = path.join(outDir, 'bundle.js');
const bundle = '/* GENERATED by build-jsx.js — do not edit. Sources, in execution order:\n'
  + files.map(function (f) { return ' *   ' + f; }).join('\n') + '\n */\n' + parts.join('\n');

// Fail the build rather than shipping a bundle that white-screens the site.
try {
  new (require('vm').Script)(bundle, { filename: 'bundle.js' });
} catch (e) {
  console.error('BUNDLE PARSE FAIL: ' + (e && e.message || e));
  console.error('A top-level const/let/class duplicated across two files will do this.');
  process.exit(1);
}
fs.writeFileSync(bundlePath, bundle);

console.log('Compiled ' + ok + ' file(s) → ' + outDir);
console.log('Bundled  ' + ok + ' file(s) → ' + bundlePath + '  ('
  + Math.round(bundle.length / 1024) + ' KB, parses OK)');
