<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class MockDataSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $pwd = Hash::make('password123');

        // ─── Cleanup any previous partial run ────────────────────────────────
        $mockEmails = [
            'hr@acleda.test', 'talent@chipmong.test', 'careers@grab.test',
            'jobs@metfone.test', 'hr@sabay.test', 'careers@totalcambodia.test',
            'hr@angkortravel.test', 'jobs@cambrew.test', 'hr@ppsez.test',
            'careers@bgh.test',
        ];
        $existingUserIds = DB::table('users')->whereIn('email', $mockEmails)->pluck('id');
        $existingCompanyIds = DB::table('companies')->whereIn('user_id', $existingUserIds)->pluck('id');
        DB::table('jobs')->whereIn('company_id', $existingCompanyIds)->delete();
        DB::table('subscriptions')->whereIn('company_id', $existingCompanyIds)->delete();
        DB::table('companies')->whereIn('id', $existingCompanyIds)->delete();
        DB::table('users')->whereIn('id', $existingUserIds)->delete();

        // ─── Companies & employer users ──────────────────────────────────────
        $companies = [
            [
                'name'       => 'ACLEDA Bank',
                'industry'   => 'Banking',
                'website'    => 'https://www.acledabank.com.kh',
                'address'    => 'No. 61, Preah Monivong Blvd, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'ACLEDA Bank is one of Cambodia\'s largest commercial banks, providing a full range of banking services including loans, deposits, and digital banking to individuals and businesses nationwide.',
                'email'      => 'hr@acleda.test',
                'contact'    => 'Sopheak Ly',
            ],
            [
                'name'       => 'Chip Mong Group',
                'industry'   => 'Construction',
                'website'    => 'https://www.chipmonggroup.com',
                'address'    => 'No. 667, Kampuchea Krom Blvd, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'Chip Mong Group is a leading conglomerate in Cambodia spanning real estate, construction materials, retail, and banking. The group employs over 5,000 people across its various subsidiaries.',
                'email'      => 'talent@chipmong.test',
                'contact'    => 'Dara Chea',
            ],
            [
                'name'       => 'Grab Cambodia',
                'industry'   => 'Technology',
                'website'    => 'https://www.grab.com/kh',
                'address'    => 'No. 33, Street 294, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'Grab Cambodia is the leading super-app in Southeast Asia offering ride-hailing, food delivery, and financial services. We are transforming the way Cambodians move, eat, and pay.',
                'email'      => 'careers@grab.test',
                'contact'    => 'Linda Nget',
            ],
            [
                'name'       => 'Metfone',
                'industry'   => 'Telecommunications',
                'website'    => 'https://www.metfone.com.kh',
                'address'    => 'No. 33, Sihanouk Blvd, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'Metfone is Cambodia\'s fastest-growing telecommunications operator, providing mobile voice, data, and enterprise solutions to millions of customers across the country.',
                'email'      => 'jobs@metfone.test',
                'contact'    => 'Kosal Phan',
            ],
            [
                'name'       => 'Sabay Digital',
                'industry'   => 'Technology',
                'website'    => 'https://www.sabay.com',
                'address'    => 'No. 64, Street 454, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'Sabay Digital is Cambodia\'s premier digital entertainment company, operating popular platforms including online games, digital payments, and media. We are building the digital future for Cambodia.',
                'email'      => 'hr@sabay.test',
                'contact'    => 'Virak Ung',
            ],
            [
                'name'       => 'Total Energies Cambodia',
                'industry'   => 'Energy',
                'website'    => 'https://www.totalenergies.com.kh',
                'address'    => 'No. 5, Street 47, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'TotalEnergies Cambodia operates a nationwide network of service stations and provides energy products and services including lubricants, LPG, and fuels to commercial and retail customers.',
                'email'      => 'careers@totalcambodia.test',
                'contact'    => 'Michel Dupont',
            ],
            [
                'name'       => 'Angkor Wat Tourism',
                'industry'   => 'Hospitality',
                'website'    => 'https://www.angkorwatravel.com',
                'address'    => 'No. 12, Charles de Gaulle Blvd, Siem Reap',
                'location_id'=> 3,
                'description'=> 'Angkor Wat Tourism is a premier travel and hospitality company based in Siem Reap, offering guided tours, hotel partnerships, and travel services to visitors exploring Cambodia\'s ancient temples.',
                'email'      => 'hr@angkortravel.test',
                'contact'    => 'Sokha Ros',
            ],
            [
                'name'       => 'Cambodia Brewery',
                'industry'   => 'Manufacturing',
                'website'    => 'https://www.cambodiabrewery.com',
                'address'    => 'Phum Prek Eng, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'Cambodia Brewery Limited is the manufacturer of Cambodia\'s most loved beers and beverages. We are part of Heineken Asia Pacific and operate state-of-the-art brewing facilities serving the local and export market.',
                'email'      => 'jobs@cambrew.test',
                'contact'    => 'Bunna Heng',
            ],
            [
                'name'       => 'Phnom Penh SEZ',
                'industry'   => 'Manufacturing',
                'website'    => 'https://www.ppsezcambodia.com',
                'address'    => 'National Road 3, Phnom Penh',
                'location_id'=> 2,
                'description'=> 'Phnom Penh Special Economic Zone (PPSEZ) is a premier industrial park hosting over 100 international factories and enterprises. We connect businesses with Cambodia\'s skilled workforce and strategic logistics.',
                'email'      => 'hr@ppsez.test',
                'contact'    => 'Vannak Sou',
            ],
            [
                'name'       => 'Battambang General Hospital',
                'industry'   => 'Healthcare',
                'website'    => 'https://www.bgh.com.kh',
                'address'    => 'No. 1, National Road 5, Battambang',
                'location_id'=> 4,
                'description'=> 'Battambang General Hospital is a leading private healthcare institution in northwest Cambodia, providing comprehensive medical services including surgery, diagnostics, and specialist consultations to patients across the region.',
                'email'      => 'careers@bgh.test',
                'contact'    => 'Dr. Sitha Chou',
            ],
        ];

        $planIds = DB::table('plans')->where('is_active', 1)->pluck('id')->toArray();

        foreach ($companies as $i => $co) {
            // Create employer user
            $userId = DB::table('users')->insertGetId([
                'role_id'           => 4, // employer
                'name'              => $co['contact'],
                'email'             => $co['email'],
                'password_hash'     => $pwd,
                'status'            => 'active',
                'email_verified_at' => $now,
                'created_at'        => $now,
                'updated_at'        => $now,
            ]);

            // Create company
            $companyId = DB::table('companies')->insertGetId([
                'user_id'     => $userId,
                'name'        => $co['name'],
                'industry'    => $co['industry'],
                'website'     => $co['website'],
                'address'     => $co['address'],
                'location_id' => $co['location_id'],
                'description' => $co['description'],
                'status'      => 'approved',
                'is_verified' => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ]);

            // Create active subscription (cycle through plans)
            $planId = $planIds[$i % count($planIds)];
            DB::table('subscriptions')->insert([
                'company_id' => $companyId,
                'plan_id'    => $planId,
                'status'     => 'active',
                'started_at' => $now->copy()->subDays(15),
                'renews_at'  => $now->copy()->addDays(rand(20, 60)),
            ]);

            // Store mapping for job creation below
            $companies[$i]['_id'] = $companyId;
        }

        // ─── Jobs ────────────────────────────────────────────────────────────
        // Categories: 1=IT, 2=Accounting, 3=Finance, 4=Marketing, 5=HR, 6=Engineering, 7=Administrative, 8=Construction
        // Locations:  2=Phnom Penh, 3=Siem Reap, 4=Battambang, 5=Takeo, 6=Prey Veng
        // Exp levels: entry, junior, mid, senior, lead, executive
        // Job types:  full_time, part_time, contract, internship

        $desc = fn(string $role, string $company, string $about) =>
            "<p><strong>About the Role</strong></p><p>We are looking for a <strong>{$role}</strong> to join {$company}. {$about}</p>";

        $req = "<ul><li>Relevant degree or equivalent practical experience</li><li>Strong communication skills in Khmer and English</li><li>Ability to work independently and in a team</li><li>Proficiency in Microsoft Office Suite</li></ul>";

        $benefits = "<ul><li>Competitive salary and annual bonus</li><li>Health insurance for employee and dependents</li><li>13th-month salary</li><li>Professional development budget</li><li>Modern office environment</li></ul>";

        $jobs = [

            // ── ACLEDA Bank ──────────────────────────────────────────────────
            [
                'company_key'      => 'ACLEDA Bank',
                'category_id'      => 3,
                'location_id'      => 2,
                'title'            => 'Senior Credit Officer',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 800,
                'salary_max'       => 1200,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Senior Credit Officer', 'ACLEDA Bank', 'You will evaluate loan applications, conduct credit analysis, and manage a portfolio of commercial and retail clients.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'ACLEDA Bank',
                'category_id'      => 1,
                'location_id'      => 2,
                'title'            => 'Core Banking Systems Developer',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 900,
                'salary_max'       => 1400,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Core Banking Systems Developer', 'ACLEDA Bank', 'Maintain and enhance our core banking platform, ensuring high availability and reliability for millions of transactions daily.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'ACLEDA Bank',
                'category_id'      => 5,
                'location_id'      => 2,
                'title'            => 'HR Business Partner',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 700,
                'salary_max'       => 1000,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('HR Business Partner', 'ACLEDA Bank', 'Partner with business leaders to drive talent acquisition, performance management, and organisational development across our branch network.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'ACLEDA Bank',
                'category_id'      => 7,
                'location_id'      => 4,
                'title'            => 'Branch Manager – Battambang',
                'job_type'         => 'full_time',
                'experience_level' => 'lead',
                'salary_min'       => 1200,
                'salary_max'       => 1800,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Branch Manager', 'ACLEDA Bank', 'Lead the Battambang branch operations, driving growth in deposits and lending while maintaining the highest standards of customer service.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Chip Mong Group ──────────────────────────────────────────────
            [
                'company_key'      => 'Chip Mong Group',
                'category_id'      => 8,
                'location_id'      => 2,
                'title'            => 'Civil Engineer – High-Rise Projects',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 700,
                'salary_max'       => 1100,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Civil Engineer', 'Chip Mong Group', 'You will oversee structural design review, site supervision, and quality control for large-scale residential and commercial high-rise projects in Phnom Penh.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Chip Mong Group',
                'category_id'      => 6,
                'location_id'      => 2,
                'title'            => 'Mechanical Engineer – Cement Plant',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 800,
                'salary_max'       => 1200,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Mechanical Engineer', 'Chip Mong Group', 'Responsible for the maintenance, repair, and optimisation of mechanical systems and heavy equipment at our cement manufacturing facility.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Chip Mong Group',
                'category_id'      => 2,
                'location_id'      => 2,
                'title'            => 'Senior Accountant',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 600,
                'salary_max'       => 900,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Senior Accountant', 'Chip Mong Group', 'Handle full-cycle accounting including monthly close, tax filing, financial reporting, and internal audit support across the group\'s subsidiaries.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Chip Mong Group',
                'category_id'      => 4,
                'location_id'      => 2,
                'title'            => 'Retail Marketing Executive',
                'job_type'         => 'full_time',
                'experience_level' => 'junior',
                'salary_min'       => 350,
                'salary_max'       => 550,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Retail Marketing Executive', 'Chip Mong Group', 'Plan and execute marketing campaigns, promotions, and events for our retail division including Chip Mong Supermarkets and Big C outlets.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Grab Cambodia ────────────────────────────────────────────────
            [
                'company_key'      => 'Grab Cambodia',
                'category_id'      => 1,
                'location_id'      => 2,
                'title'            => 'Senior Android Developer',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 1500,
                'salary_max'       => 2500,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'is_remote'        => 0,
                'description'      => $desc('Senior Android Developer', 'Grab Cambodia', 'Build and maintain Grab\'s Android super-app, shipping features used by millions of riders, drivers, and merchants daily. You will own key modules from design to production.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Grab Cambodia',
                'category_id'      => 1,
                'location_id'      => 2,
                'title'            => 'Data Analyst – Merchant Growth',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 1000,
                'salary_max'       => 1600,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'is_remote'        => 1,
                'description'      => $desc('Data Analyst', 'Grab Cambodia', 'Analyse merchant and consumer behaviour data to surface insights that drive GrabFood\'s merchant growth strategy across Cambodia.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Grab Cambodia',
                'category_id'      => 4,
                'location_id'      => 2,
                'title'            => 'Performance Marketing Manager',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 1200,
                'salary_max'       => 2000,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Performance Marketing Manager', 'Grab Cambodia', 'Own digital performance campaigns across Meta, Google, and TikTok, driving user acquisition and retention at efficient CPAs for GrabFood and GrabCar.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Grab Cambodia',
                'category_id'      => 1,
                'location_id'      => 2,
                'title'            => 'Junior QA Engineer',
                'job_type'         => 'full_time',
                'experience_level' => 'junior',
                'salary_min'       => 600,
                'salary_max'       => 900,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Junior QA Engineer', 'Grab Cambodia', 'Write and execute manual and automated test cases for Grab\'s mobile and backend systems, ensuring every release meets the highest quality bar.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Metfone ──────────────────────────────────────────────────────
            [
                'company_key'      => 'Metfone',
                'category_id'      => 6,
                'location_id'      => 2,
                'title'            => 'Network Planning Engineer',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 700,
                'salary_max'       => 1100,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Network Planning Engineer', 'Metfone', 'Plan and optimise our 4G/5G radio network across Cambodia, conducting site surveys, capacity planning, and interference analysis to deliver best-in-class coverage.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Metfone',
                'category_id'      => 4,
                'location_id'      => 2,
                'title'            => 'Brand & Communications Manager',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 1000,
                'salary_max'       => 1500,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Brand & Communications Manager', 'Metfone', 'Define and protect the Metfone brand through integrated marketing campaigns, PR, and digital content strategies that resonate with Cambodia\'s diverse customer base.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Metfone',
                'category_id'      => 3,
                'location_id'      => 2,
                'title'            => 'Financial Planning & Analysis Specialist',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 700,
                'salary_max'       => 1000,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('FP&A Specialist', 'Metfone', 'Support financial planning, budgeting, and forecasting processes, providing analytical insights to senior leadership to drive business performance.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Metfone',
                'category_id'      => 1,
                'location_id'      => 3,
                'title'            => 'IT Support Technician – Siem Reap',
                'job_type'         => 'full_time',
                'experience_level' => 'junior',
                'salary_min'       => 300,
                'salary_max'       => 500,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('IT Support Technician', 'Metfone', 'Provide first- and second-level hardware, software, and network support to Metfone staff and retail outlets across Siem Reap province.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Sabay Digital ────────────────────────────────────────────────
            [
                'company_key'      => 'Sabay Digital',
                'category_id'      => 1,
                'location_id'      => 2,
                'title'            => 'Full-Stack Web Developer (Laravel + Vue)',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 800,
                'salary_max'       => 1400,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'is_remote'        => 1,
                'description'      => $desc('Full-Stack Developer', 'Sabay Digital', 'Join our engineering team building Cambodia\'s leading digital platforms. You will ship features for our gaming and payment products serving hundreds of thousands of active users.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Sabay Digital',
                'category_id'      => 1,
                'location_id'      => 2,
                'title'            => 'Game Designer',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 700,
                'salary_max'       => 1100,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Game Designer', 'Sabay Digital', 'Design engaging game mechanics, progression systems, and monetisation flows for our online and mobile games targeting the Cambodian and Southeast Asian market.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Sabay Digital',
                'category_id'      => 4,
                'location_id'      => 2,
                'title'            => 'Social Media Content Creator',
                'job_type'         => 'full_time',
                'experience_level' => 'entry',
                'salary_min'       => 250,
                'salary_max'       => 400,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Social Media Content Creator', 'Sabay Digital', 'Create compelling short-form video, graphic, and written content in Khmer and English for Sabay\'s social channels and gaming promotions.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Sabay Digital',
                'category_id'      => 1,
                'location_id'      => 2,
                'title'            => 'DevOps / Cloud Engineer',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 1200,
                'salary_max'       => 2000,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'is_remote'        => 1,
                'description'      => $desc('DevOps / Cloud Engineer', 'Sabay Digital', 'Own our AWS infrastructure, CI/CD pipelines, and site reliability engineering practices. Help us scale to handle peak gaming events with zero downtime.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Total Energies Cambodia ───────────────────────────────────────
            [
                'company_key'      => 'Total Energies Cambodia',
                'category_id'      => 6,
                'location_id'      => 2,
                'title'            => 'HSE Engineer',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 900,
                'salary_max'       => 1400,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('HSE Engineer', 'TotalEnergies Cambodia', 'Ensure health, safety, and environmental compliance across our fuel depots and service station network, implementing group HSE standards and local regulations.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Total Energies Cambodia',
                'category_id'      => 3,
                'location_id'      => 2,
                'title'            => 'Treasury & Cash Management Officer',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 700,
                'salary_max'       => 1000,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Treasury Officer', 'TotalEnergies Cambodia', 'Manage daily cash positions, bank reconciliations, and treasury operations in coordination with the regional finance team across Southeast Asia.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Total Energies Cambodia',
                'category_id'      => 4,
                'location_id'      => 2,
                'title'            => 'Lubricants Sales Representative',
                'job_type'         => 'full_time',
                'experience_level' => 'junior',
                'salary_min'       => 400,
                'salary_max'       => 700,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Lubricants Sales Representative', 'TotalEnergies Cambodia', 'Build and manage a B2B client portfolio in the automotive and industrial sectors, promoting TotalEnergies lubricant products across Phnom Penh and surrounding provinces.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Angkor Wat Tourism ────────────────────────────────────────────
            [
                'company_key'      => 'Angkor Wat Tourism',
                'category_id'      => 4,
                'location_id'      => 3,
                'title'            => 'Tour Operations Manager',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 700,
                'salary_max'       => 1100,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Tour Operations Manager', 'Angkor Wat Tourism', 'Oversee daily tour logistics, guide management, and partnerships with hotels and transport providers to deliver exceptional visitor experiences at Cambodia\'s heritage sites.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Angkor Wat Tourism',
                'category_id'      => 7,
                'location_id'      => 3,
                'title'            => 'Guest Relations Officer',
                'job_type'         => 'full_time',
                'experience_level' => 'entry',
                'salary_min'       => 250,
                'salary_max'       => 400,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Guest Relations Officer', 'Angkor Wat Tourism', 'Welcome international visitors, handle bookings, and provide seamless concierge support to ensure every guest has an unforgettable experience in Siem Reap.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Angkor Wat Tourism',
                'category_id'      => 1,
                'location_id'      => 3,
                'title'            => 'Digital Booking Platform Developer',
                'job_type'         => 'contract',
                'experience_level' => 'mid',
                'salary_min'       => 800,
                'salary_max'       => 1200,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'is_remote'        => 1,
                'description'      => $desc('Booking Platform Developer', 'Angkor Wat Tourism', 'Build and maintain our online tour booking portal integrating with major OTAs, payment gateways, and our internal tour management system.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Cambodia Brewery ─────────────────────────────────────────────
            [
                'company_key'      => 'Cambodia Brewery',
                'category_id'      => 6,
                'location_id'      => 2,
                'title'            => 'Production Engineer – Brewing',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 800,
                'salary_max'       => 1300,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Production Engineer', 'Cambodia Brewery Limited', 'Manage daily brewing operations, optimise production processes, and ensure product quality meets Heineken global standards at our Phnom Penh facility.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Cambodia Brewery',
                'category_id'      => 4,
                'location_id'      => 2,
                'title'            => 'Key Account Manager – On-Trade',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 900,
                'salary_max'       => 1400,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Key Account Manager', 'Cambodia Brewery Limited', 'Own relationships with top-tier bar, restaurant, and hotel accounts, driving volume growth and perfect execution of Cambodia Beer and Heineken brands.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Cambodia Brewery',
                'category_id'      => 5,
                'location_id'      => 2,
                'title'            => 'Training & Development Specialist',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 600,
                'salary_max'       => 900,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Training & Development Specialist', 'Cambodia Brewery Limited', 'Design and deliver training programmes for factory staff, sales teams, and management, supporting our culture of continuous improvement and people development.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Cambodia Brewery',
                'category_id'      => 2,
                'location_id'      => 2,
                'title'            => 'Cost Accountant',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 600,
                'salary_max'       => 850,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Cost Accountant', 'Cambodia Brewery Limited', 'Monitor and analyse manufacturing costs, perform variance analysis, and support monthly management reporting for our brewing and distribution operations.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Phnom Penh SEZ ───────────────────────────────────────────────
            [
                'company_key'      => 'Phnom Penh SEZ',
                'category_id'      => 7,
                'location_id'      => 2,
                'title'            => 'Zone Development Officer',
                'job_type'         => 'full_time',
                'experience_level' => 'mid',
                'salary_min'       => 600,
                'salary_max'       => 1000,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Zone Development Officer', 'Phnom Penh SEZ', 'Support business development and investor relations for our industrial zone, facilitating factory setup, licensing, and ongoing tenant services for international manufacturers.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Phnom Penh SEZ',
                'category_id'      => 6,
                'location_id'      => 2,
                'title'            => 'Facilities & Infrastructure Engineer',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 1000,
                'salary_max'       => 1600,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Facilities Engineer', 'Phnom Penh SEZ', 'Manage the zone\'s utilities infrastructure — power, water, roads, and telecoms — ensuring uninterrupted services for over 100 tenant factories.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Phnom Penh SEZ',
                'category_id'      => 3,
                'location_id'      => 2,
                'title'            => 'Finance Analyst – Investor Incentives',
                'job_type'         => 'full_time',
                'experience_level' => 'junior',
                'salary_min'       => 400,
                'salary_max'       => 650,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Finance Analyst', 'Phnom Penh SEZ', 'Model investment incentive packages for prospective tenants, conduct ROI analysis, and support financial due diligence for new factory investments in the zone.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],

            // ── Battambang General Hospital ──────────────────────────────────
            [
                'company_key'      => 'Battambang General Hospital',
                'category_id'      => 5,
                'location_id'      => 4,
                'title'            => 'HR & Payroll Officer',
                'job_type'         => 'full_time',
                'experience_level' => 'junior',
                'salary_min'       => 300,
                'salary_max'       => 500,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('HR & Payroll Officer', 'Battambang General Hospital', 'Manage end-to-end payroll processing, leave administration, and staff recruitment for our 300+ medical and administrative staff.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Battambang General Hospital',
                'category_id'      => 7,
                'location_id'      => 4,
                'title'            => 'Hospital Administrator',
                'job_type'         => 'full_time',
                'experience_level' => 'senior',
                'salary_min'       => 800,
                'salary_max'       => 1200,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 1,
                'description'      => $desc('Hospital Administrator', 'Battambang General Hospital', 'Oversee the operational management of the hospital, including patient services, billing, procurement, and coordination with department heads to deliver quality healthcare.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Battambang General Hospital',
                'category_id'      => 2,
                'location_id'      => 4,
                'title'            => 'Medical Billing Specialist',
                'job_type'         => 'full_time',
                'experience_level' => 'entry',
                'salary_min'       => 250,
                'salary_max'       => 400,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('Medical Billing Specialist', 'Battambang General Hospital', 'Process patient invoices, manage insurance claims, and reconcile billing records to ensure accurate and timely revenue collection for the hospital.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
            [
                'company_key'      => 'Battambang General Hospital',
                'category_id'      => 1,
                'location_id'      => 4,
                'title'            => 'Health Information Systems Officer',
                'job_type'         => 'full_time',
                'experience_level' => 'junior',
                'salary_min'       => 350,
                'salary_max'       => 550,
                'salary_currency'  => 'USD',
                'salary_period'    => 'month',
                'is_featured'      => 0,
                'description'      => $desc('HIS Officer', 'Battambang General Hospital', 'Maintain and support the hospital information system (HIS), manage patient data integrity, and train clinical staff on digital records management.'),
                'requirements'     => $req,
                'benefits'         => $benefits,
            ],
        ];

        // Build company name → id map
        $companyMap = [];
        foreach ($companies as $co) {
            $companyMap[$co['name']] = $co['_id'];
        }

        // Insert jobs
        foreach ($jobs as $job) {
            $companyId = $companyMap[$job['company_key']] ?? null;
            if (!$companyId) continue;

            $title = $job['title'];
            // Simple slug generation
            $slug = strtolower(preg_replace('/[^a-z0-9]+/i', '-', $title));
            $slug = trim($slug, '-');
            // Ensure unique slug
            $exists = DB::table('jobs')->where('slug', $slug)->exists();
            if ($exists) { $slug = $slug . '-' . $companyId; }

            DB::table('jobs')->insert([
                'company_id'       => $companyId,
                'category_id'      => $job['category_id'],
                'location_id'      => $job['location_id'],
                'title'            => $title,
                'slug'             => $slug,
                'job_type'         => $job['job_type'],
                'experience_level' => $job['experience_level'],
                'salary_min'       => $job['salary_min'],
                'salary_max'       => $job['salary_max'],
                'salary_currency'  => $job['salary_currency'],
                'salary_period'    => $job['salary_period'],
                'is_remote'        => $job['is_remote'] ?? 0,
                'is_featured'      => $job['is_featured'],
                'description'      => $job['description'],
                'requirements'     => $job['requirements'],
                'benefits'         => $job['benefits'],
                'status'           => 'published',
                'views'            => rand(10, 800),
                'expires_at'       => $now->copy()->addDays(rand(20, 60))->toDateString(),
                'published_at'     => $now->copy()->subDays(rand(1, 30)),
                'created_at'       => $now,
                'updated_at'       => $now,
            ]);
        }

        $this->command->info('Mock data seeded: ' . count($companies) . ' companies, ' . count($jobs) . ' jobs.');
    }
}
