<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Database health improvements — indexes, constraints, type corrections.
 * Generated by database health audit 2026-06-22.
 */
return new class extends Migration
{
    public function up(): void
    {
        // ── auth_tokens ───────────────────────────────────────────────────────
        // CRITICAL: token_hash lookup was a full table scan on every auth refresh
        Schema::table('auth_tokens', function (Blueprint $table) {
            $table->index('token_hash', 'idx_token_hash');
            $table->index('expires_at', 'idx_token_expires');
        });

        // ── jobs ──────────────────────────────────────────────────────────────
        // Composite index for main public listing: WHERE status='published' ORDER BY is_featured DESC, created_at DESC
        Schema::table('jobs', function (Blueprint $table) {
            $table->index(['status', 'is_featured', 'created_at'], 'idx_jobs_status_featured_date');
            // Composite for employer's own job list: WHERE company_id=? AND status=?
            $table->index(['company_id', 'status'], 'idx_jobs_company_status');
            // Unique slug — prevents two jobs sharing the same URL slug
            $table->unique('slug', 'uq_jobs_slug');
        });

        // ── subscriptions ─────────────────────────────────────────────────────
        // Composite for plan-limit check on every job post: WHERE company_id=? AND status='active'
        Schema::table('subscriptions', function (Blueprint $table) {
            $table->index(['company_id', 'status'], 'idx_sub_company_status');
            $table->index('status', 'idx_sub_status');
        });

        // ── applications ──────────────────────────────────────────────────────
        // Candidate dashboard filters by stage
        Schema::table('applications', function (Blueprint $table) {
            $table->index(['candidate_id', 'stage'], 'idx_app_candidate_stage');
            // Employer pipeline: applications for a job filtered by stage
            $table->index(['job_id', 'stage'], 'idx_app_job_stage');
        });

        // ── payments ──────────────────────────────────────────────────────────
        Schema::table('payments', function (Blueprint $table) {
            $table->index(['company_id', 'status'], 'idx_pay_company_status');
            $table->index('status', 'idx_pay_status');
        });

        // ── notifications ─────────────────────────────────────────────────────
        // Fetch unread notifications for a user
        Schema::table('notifications', function (Blueprint $table) {
            $table->index(['user_id', 'read_at'], 'idx_notif_user_read');
        });

        // ── social_accounts ───────────────────────────────────────────────────
        // Prevent duplicate provider accounts per user
        Schema::table('social_accounts', function (Blueprint $table) {
            $table->unique(['user_id', 'provider'], 'uq_social_user_provider');
        });

        // ── users ─────────────────────────────────────────────────────────────
        // Admin candidate listing filters by status
        Schema::table('users', function (Blueprint $table) {
            $table->index('status', 'idx_users_status');
        });

        // ── banners ───────────────────────────────────────────────────────────
        // Active banner lookup filters is_active + date range
        Schema::table('banners', function (Blueprint $table) {
            $table->index(['is_active', 'starts_at', 'ends_at'], 'idx_banners_active_dates');
            $table->index('sort_order', 'idx_banners_sort');
        });

        // ── settings ──────────────────────────────────────────────────────────
        // Lookup by group (common) should be fast
        Schema::table('settings', function (Blueprint $table) {
            $table->index('group', 'idx_settings_group');
        });

        // ── plans.features_json → JSON type ──────────────────────────────────
        // Convert longtext to proper JSON — enables path queries and auto-validation
        DB::statement("ALTER TABLE plans MODIFY COLUMN features_json JSON NULL");

        // ── resumes.data → JSON type ──────────────────────────────────────────
        DB::statement("ALTER TABLE resumes MODIFY COLUMN data JSON NULL");

        // ── plans: tighten int sizes ──────────────────────────────────────────
        DB::statement("ALTER TABLE plans MODIFY COLUMN job_post_limit SMALLINT UNSIGNED NULL");
        DB::statement("ALTER TABLE plans MODIFY COLUMN featured_credits SMALLINT UNSIGNED NOT NULL DEFAULT 0");

        // ── resume_sections.sort_order: tighten ───────────────────────────────
        DB::statement("ALTER TABLE resume_sections MODIFY COLUMN sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0");

        // ── banners.sort_order: tighten ────────────────────────────────────────
        DB::statement("ALTER TABLE banners MODIFY COLUMN sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0");
    }

    public function down(): void
    {
        Schema::table('auth_tokens', function (Blueprint $table) {
            $table->dropIndex('idx_token_hash');
            $table->dropIndex('idx_token_expires');
        });
        Schema::table('jobs', function (Blueprint $table) {
            $table->dropIndex('idx_jobs_status_featured_date');
            $table->dropIndex('idx_jobs_company_status');
            $table->dropUnique('uq_jobs_slug');
        });
        Schema::table('subscriptions', function (Blueprint $table) {
            $table->dropIndex('idx_sub_company_status');
            $table->dropIndex('idx_sub_status');
        });
        Schema::table('applications', function (Blueprint $table) {
            $table->dropIndex('idx_app_candidate_stage');
            $table->dropIndex('idx_app_job_stage');
        });
        Schema::table('payments', function (Blueprint $table) {
            $table->dropIndex('idx_pay_company_status');
            $table->dropIndex('idx_pay_status');
        });
        Schema::table('notifications', function (Blueprint $table) {
            $table->dropIndex('idx_notif_user_read');
        });
        Schema::table('social_accounts', function (Blueprint $table) {
            $table->dropUnique('uq_social_user_provider');
        });
        Schema::table('users', function (Blueprint $table) {
            $table->dropIndex('idx_users_status');
        });
        Schema::table('banners', function (Blueprint $table) {
            $table->dropIndex('idx_banners_active_dates');
            $table->dropIndex('idx_banners_sort');
        });
        Schema::table('settings', function (Blueprint $table) {
            $table->dropIndex('idx_settings_group');
        });

        DB::statement("ALTER TABLE plans MODIFY COLUMN features_json LONGTEXT NULL");
        DB::statement("ALTER TABLE resumes MODIFY COLUMN data LONGTEXT NULL");
        DB::statement("ALTER TABLE plans MODIFY COLUMN job_post_limit INT(11) NULL");
        DB::statement("ALTER TABLE plans MODIFY COLUMN featured_credits INT(11) NOT NULL DEFAULT 0");
        DB::statement("ALTER TABLE resume_sections MODIFY COLUMN sort_order INT(11) NOT NULL DEFAULT 0");
        DB::statement("ALTER TABLE banners MODIFY COLUMN sort_order INT(11) NOT NULL DEFAULT 0");
    }
};
